-- runghc 08-1.hs < 08.in.txt

{-
--- Day 8: Resonant Collinearity ---

You find yourselves on the roof of a top-secret Easter Bunny installation.

While The Historians do their thing, you take a look at the familiar huge antenna. Much to your surprise, it seems to have been reconfigured to emit a signal that makes people 0.1% more likely to buy Easter Bunny brand Imitation Mediocre Chocolate as a Christmas gift! Unthinkable!

Scanning across the city, you find that there are actually many such antennas. Each antenna is tuned to a specific frequency indicated by a single lowercase letter, uppercase letter, or digit. You create a map (your puzzle input) of these antennas. For example:

............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............

The signal only applies its nefarious effect at specific antinodes based on the resonant frequencies of the antennas. In particular, an antinode occurs at any point that is perfectly in line with two antennas of the same frequency - but only when one of the antennas is twice as far away as the other. This means that for any pair of antennas with the same frequency, there are two antinodes, one on either side of them.

So, for these two antennas with frequency a, they create the two antinodes marked with #:

..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........

Adding a third antenna with the same frequency creates several more antinodes. It would ideally add four antinodes, but two are off the right side of the map, so instead it adds only two:

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
..........

Antennas with different frequencies don't create antinodes; A and a count as different frequencies. However, antinodes can occur at locations that contain antennas. In this diagram, the lone antenna with frequency capital A creates no antinodes but has a lowercase-a-frequency antinode at its location:

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......A...
..........
..........

The first example has antennas with two different frequencies, so the antinodes they create look like this, plus an antinode overlapping the topmost A-frequency antenna:

......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....A.....
...#........
#......#....
........A...
.........A..
..........#.
..........#.

Because the topmost A-frequency antenna overlaps with a 0-frequency antinode, there are 14 total unique locations that contain an antinode within the bounds of the map.

Calculate the impact of the signal. How many unique locations within the bounds of the map contain an antinode?
-}

import Data.List

type Pos = (Int, Int)
data Antenna = Antenna Char Pos

antinodes :: [Antenna] -> [Pos]
antinodes = concatMap (concatMap pairAntinodes . pairs . map (\(Antenna _ pos) -> pos)) . groupBy eqFreq . sortBy ordFreq
  where
    ordFreq (Antenna f1 _) (Antenna f2 _) =  compare f1 f2
    eqFreq (Antenna f1 _) (Antenna f2 _) = f1 == f2
    pairs [] = []
    pairs (x : xs) = [(x, y) | y <- xs] ++ pairs xs
    pairAntinodes ((r1, c1), (r2, c2)) = [(2 * r1 - r2, 2 * c1 - c2), (2 * r2 - r1, 2 * c2 - c1)]

main = interact $ show . length . nub . helper
  where
    helper file = filter inCity $ antinodes antennas
      where
        city = [Antenna f (r, c) | (r, line) <- zip [1 ..] (lines file), (c, f) <- zip [1 ..] line]
        (rows, cols, antennas) = foldr visit (0, 0, []) city
        inCity (r, c) = 0 < r && r <= rows && 0 < c && c <= cols
        visit x@(Antenna f (r, c)) (rows, cols, antennas) =
            (max rows r, max cols c, if f == '.' then antennas else x : antennas)
